import { Painting } from './types';

export const FAMOUS_PAINTINGS: Painting[] = [
  {
    id: 'birth-venus',
    title: 'The Birth of Venus',
    artist: 'Sandro Botticelli',
    year: '1485',
    category: 'Renaissance',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg',
    description: 'A landmark of the early Renaissance, depicting the goddess Venus arriving at the shore after her birth.',
  },
  {
    id: 'night-watch',
    title: 'The Night Watch',
    artist: 'Rembrandt van Rijn',
    year: '1642',
    category: 'Baroque',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_P001594_-_The_Rijksmuseum.jpg/1280px-The_Night_Watch_-_P001594_-_The_Rijksmuseum.jpg',
    description: 'A masterpiece of the Dutch Golden Age, famous for its colossal size and dramatic use of light and shadow.',
  },
  {
    id: 'girl-pearl-earring',
    title: 'Girl with a Pearl Earring',
    artist: 'Johannes Vermeer',
    year: '1665',
    category: 'Baroque',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Johannes_Vermeer_%281632-1675%29_-_The_Girl_With_The_Pearl_Earring_%281665%29.jpg/800px-Johannes_Vermeer_%281632-1675%29_-_The_Girl_With_The_Pearl_Earring_%281665%29.jpg',
    description: 'Often called the "Mona Lisa of the North," this painting is a masterful study of light and texture.',
  },
  {
    id: 'starry-night',
    title: 'The Starry Night',
    artist: 'Vincent van Gogh',
    year: '1889',
    category: 'Post-Impressionism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg',
    description: 'Expressive swirls and high contrast, representing the view from Van Gogh\'s asylum room window.',
  },
  {
    id: 'mona-lisa',
    title: 'Mona Lisa',
    artist: 'Leonardo da Vinci',
    year: '1503',
    category: 'Renaissance',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg',
    description: 'The world\'s most famous portrait, known for the subject\'s enigmatic expression and sfumato technique.',
  },
  {
    id: 'wanderer-sea-fog',
    title: 'Wanderer above the Sea of Fog',
    artist: 'Caspar David Friedrich',
    year: '1818',
    category: 'Romanticism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/1280px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg',
    description: 'A quintessential Romantic masterpiece exploring the sublime relationship between man and nature.',
  },
  {
    id: 'nighthawks',
    title: 'Nighthawks',
    artist: 'Edward Hopper',
    year: '1942',
    category: 'Realism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg/1280px-Nighthawks_by_Edward_Hopper_1942.jpg',
    description: 'Iconic American realism showcasing urban isolation and the stark light of a late-night diner.',
  },
  {
    id: 'persistence-memory',
    title: 'The Persistence of Memory',
    artist: 'Salvador Dalí',
    year: '1931',
    category: 'Modern',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/The_Persistence_of_Memory.jpg/800px-The_Persistence_of_Memory.jpg',
    description: 'The defining Surrealist work, exploring the fluidity of time through iconic melting clocks.',
  },
  {
    id: 'the-kiss',
    title: 'The Kiss',
    artist: 'Gustav Klimt',
    year: '1907',
    category: 'Modern',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Art_Project.jpg/1280px-The_Kiss_-_Gustav_Klimt_-_Google_Art_Project.jpg',
    description: 'An icon of Art Nouveau, blending eroticism with geometric abstraction and gold leaf.',
  },
  {
    id: 'great-wave',
    title: 'The Great Wave off Kanagawa',
    artist: 'Hokusai',
    year: '1831',
    category: 'Romanticism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Great_Wave_off_Kanagawa2.jpg/1280px-Great_Wave_off_Kanagawa2.jpg',
    description: 'A world-famous ukiyo-e woodblock print featuring a massive wave and Mount Fuji.',
  },
  {
    id: 'school-athens',
    title: 'The School of Athens',
    artist: 'Raphael',
    year: '1509',
    category: 'Renaissance',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/i/ip/Sanzio_01.jpg/1280px-Sanzio_01.jpg',
    description: 'A grand example of architectural perspective representing the greatest philosophers of antiquity.',
  },
  {
    id: 'guernica',
    title: 'Guernica',
    artist: 'Pablo Picasso',
    year: '1937',
    category: 'Modern',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Picasso_-_Guernica.jpg/1280px-Picasso_-_Guernica.jpg',
    description: 'A powerful anti-war painting utilizing cubist distortion to convey chaos and suffering.',
  },
  {
    id: 'scream',
    title: 'The Scream',
    artist: 'Edvard Munch',
    year: '1893',
    category: 'Expressionism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/800px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg',
    description: 'An agonizing scream of nature, characterized by its high-key color palette and swirling shapes.',
  },
  {
    id: 'impression-sunrise',
    title: 'Impression, Sunrise',
    artist: 'Claude Monet',
    year: '1872',
    category: 'Impressionism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/1280px-Monet_-_Impression%2C_Sunrise.jpg',
    description: 'The painting that gave the Impressionist movement its name, emphasizing light over literal form.',
  },
  {
    id: 'las-meninas',
    title: 'Las Meninas',
    artist: 'Diego Velázquez',
    year: '1656',
    category: 'Baroque',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg/1280px-Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg',
    description: 'A complex composition exploring the relationships between viewer, painter, and royal subjects.',
  },
  {
    id: 'american-gothic',
    title: 'American Gothic',
    artist: 'Grant Wood',
    year: '1930',
    category: 'Realism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg/800px-Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg',
    description: 'An iconic representation of rural American life, known for its stark and detailed realism.',
  },
  {
    id: 'the-swing',
    title: 'The Swing',
    artist: 'Jean-Honoré Fragonard',
    year: '1767',
    category: 'Modern',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_WGA8235.jpg/1280px-Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_WGA8235.jpg',
    description: 'A quintessential Rococo masterpiece representing the era\'s lightness and playful atmosphere.',
  },
  {
    id: 'garden-earthly-delights',
    title: 'The Garden of Earthly Delights',
    artist: 'Hieronymus Bosch',
    year: '1490',
    category: 'Renaissance',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/El_jard%C3%ADn_de_las_delicias%2C_de_El_Bosco.jpg/1280px-El_jard%C3%ADn_de_las_delicias%2C_de_El_Bosco.jpg',
    description: 'A surreal and dense triptych pre-dating modern surrealism by centuries.',
  },
  {
    id: 'last-supper',
    title: 'The Last Supper',
    artist: 'Leonardo da Vinci',
    year: '1495',
    category: 'Renaissance',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Ultima_Cena_-_Leonardo_Da_Vinci_-_High_Resolution_Mirror_Reflection.jpg/1280px-Ultima_Cena_-_Leonardo_Da_Vinci_-_High_Resolution_Mirror_Reflection.jpg',
    description: 'A monumental mural showcasing Da Vinci\'s mastery of perspective and psychological depth.',
  },
  {
    id: 'liberty-leading',
    title: 'Liberty Leading the People',
    artist: 'Eugène Delacroix',
    year: '1830',
    category: 'Romanticism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_Le_28_juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/1280px-Eug%C3%A8ne_Delacroix_-_Le_28_juillet._La_Libert%C3%A9_guidant_le_peuple.jpg',
    description: 'A dramatic work commemorating the July Revolution of 1830 in France.',
  },
  {
    id: 'lady-ermine',
    title: 'Lady with an Ermine',
    artist: 'Leonardo da Vinci',
    year: '1489',
    category: 'Renaissance',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Lady_with_an_Ermine_-_Leonardo_da_Vinci_-_Google_Art_Project.jpg/1280px-Lady_with_an_Ermine_-_Leonardo_da_Vinci_-_Google_Art_Project.jpg',
    description: 'A masterpiece of portraiture showing early use of lighting to define three-dimensional form.',
  },
  {
    id: 'ophelia',
    title: 'Ophelia',
    artist: 'John Everett Millais',
    year: '1851',
    category: 'Romanticism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg/1280px-John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg',
    description: 'A Pre-Raphaelite work known for its meticulous detail and tragic cinematic atmosphere.',
  },
  {
    id: 'sunday-la-grande-jatte',
    title: 'A Sunday on La Grande Jatte',
    artist: 'Georges Seurat',
    year: '1884',
    category: 'Post-Impressionism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/1280px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg',
    description: 'The definitive example of pointillism, using millions of dots to create a vibrant scene.',
  },
  {
    id: 'napoleon-crossing',
    title: 'Napoleon Crossing the Alps',
    artist: 'Jacques-Louis David',
    year: '1801',
    category: 'Romanticism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Napoleon_4.jpg/800px-Napoleon_4.jpg',
    description: 'A heroic equestrian portrait symbolizing Napoleon\'s military genius and power.',
  },
  {
    id: 'arnolfini-portrait',
    title: 'The Arnolfini Portrait',
    artist: 'Jan van Eyck',
    year: '1434',
    category: 'Renaissance',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/800px-Van_Eyck_-_Arnolfini_Portrait.jpg',
    description: 'Famous for its intricate detail and masterfully handled reflection in the mirror.',
  },
  {
    id: 'anatomy-lesson',
    title: 'The Anatomy Lesson of Dr. Nicolaes Tulp',
    artist: 'Rembrandt van Rijn',
    year: '1632',
    category: 'Baroque',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg/1280px-Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg',
    description: 'A revolutionary group portrait that created a sense of focused narrative action.',
  },
  {
    id: 'the-bedroom',
    title: 'The Bedroom',
    artist: 'Vincent van Gogh',
    year: '1888',
    category: 'Post-Impressionism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg/1280px-Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg',
    description: 'A study in color and simplified form, meant to evoke sense of domestic comfort.',
  },
  {
    id: 'lady-of-shalott',
    title: 'The Lady of Shalott',
    artist: 'John William Waterhouse',
    year: '1888',
    category: 'Romanticism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project.jpg/1280px-John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project.jpg',
    description: 'A masterpiece capturing a tragic moment from Tennyson\'s poem with rich cinematic color.',
  },
  {
    id: 'raft-medusa',
    title: 'The Raft of the Medusa',
    artist: 'Théodore Géricault',
    year: '1818',
    category: 'Romanticism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg/1280px-JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg',
    description: 'An icon of French Romanticism famous for its grand scale and tragic energy.',
  },
  {
    id: 'olympia',
    title: 'Olympia',
    artist: 'Édouard Manet',
    year: '1863',
    category: 'Realism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Edouard_Manet_-_Olympia_-_Google_Art_Project.jpg/1280px-Edouard_Manet_-_Olympia_-_Google_Art_Project.jpg',
    description: 'A controversial work that challenged academic traditions with its confrontational subject.',
  },
  {
    id: 'bal-moulin-galette',
    title: 'Bal du moulin de la Galette',
    artist: 'Pierre-Auguste Renoir',
    year: '1876',
    category: 'Impressionism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Pierre-Auguste_Renoir%2C_Bal_du_moulin_de_la_Galette%2C_1876%2C_Mus%C3%A9e_d%27Orsay.jpg/1280px-Pierre-Auguste_Renoir%2C_Bal_du_moulin_de_la_Galette%2C_1876%2C_Mus%C3%A9e_d%27Orsay.jpg',
    description: 'One of Impressionism\'s most celebrated works, capturing modern life in Montmartre.',
  },
  {
    id: 'the-blue-boy',
    title: 'The Blue Boy',
    artist: 'Thomas Gainsborough',
    year: '1770',
    category: 'Modern',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Thomas_Gainsborough_-_The_Blue_Boy.jpg/800px-Thomas_Gainsborough_-_The_Blue_Boy.jpg',
    description: 'A masterful study in blue tones and elegant staging, representing 18th-century English portraiture.',
  },
  {
    id: 'saturn-devouring',
    title: 'Saturn Devouring His Son',
    artist: 'Francisco Goya',
    year: '1823',
    category: 'Romanticism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/800px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg',
    description: 'A terrifying work from Goya\'s "Black Paintings," full of raw emotion.',
  },
  {
    id: 'the-dance',
    title: 'The Dance (II)',
    artist: 'Henri Matisse',
    year: '1910',
    category: 'Modern',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Matisse_The_Dance.jpg/1280px-Matisse_The_Dance.jpg',
    description: 'A Fauvist celebration of movement and primary color using primal visual energy.',
  },
  {
    id: 'calling-st-matthew',
    title: 'The Calling of St Matthew',
    artist: 'Caravaggio',
    year: '1600',
    category: 'Baroque',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/The_Calling_of_Saint_Matthew_-_Caravaggio.jpg/1280px-The_Calling_of_Saint_Matthew_-_Caravaggio.jpg',
    description: 'A revolutionary use of Tenebrism acting as a directional focal point.',
  },
  {
    id: 'the-ambassadors',
    title: 'The Ambassadors',
    artist: 'Hans Holbein the Younger',
    year: '1533',
    category: 'Renaissance',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg/1280px-Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg',
    description: 'Famous for its anamorphic skull and masterclass in symbolic blocking.',
  },
  {
    id: 'view-delft',
    title: 'View of Delft',
    artist: 'Johannes Vermeer',
    year: '1660',
    category: 'Baroque',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Johannes_Vermeer_-_View_of_Delft_-_Google_Art_Project.jpg/1280px-Johannes_Vermeer_-_View_of_Delft_-_Google_Art_Project.jpg',
    description: 'A rare and masterfully lit cityscape celebrated for its naturalistic light.',
  },
  {
    id: 'yellow-red-blue',
    title: 'Yellow-Red-Blue',
    artist: 'Wassily Kandinsky',
    year: '1925',
    category: 'Modern',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Vassily_Kandinsky%2C_1925_-_Jaune-Rouge-Bleu.jpg/1280px-Vassily_Kandinsky%2C_1925_-_Jaune-Rouge-Bleu.jpg',
    description: 'An abstract exploration of geometric forms and primary colors.',
  },
  {
    id: 'third-july',
    title: 'The Third of May 1808',
    artist: 'Francisco Goya',
    year: '1814',
    category: 'Romanticism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/El_tres_de_mayo_de_1808_en_Madrid.jpg/1280px-El_tres_de_mayo_de_1808_en_Madrid.jpg',
    description: 'A groundbreaking work of social commentary with dramatic lighting.',
  },
  {
    id: 'napoleon-david',
    title: 'The Death of Marat',
    artist: 'Jacques-Louis David',
    year: '1793',
    category: 'Romanticism',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Jacques-Louis_David_-_La_Mort_de_Marat.jpg/1280px-Jacques-Louis_David_-_La_Mort_de_Marat.jpg',
    description: 'An icon of the French Revolution, elevating political assassination to martyrdom.',
  }
];

export const CATEGORIES = ['All', 'Renaissance', 'Baroque', 'Romanticism', 'Impressionism', 'Post-Impressionism', 'Realism', 'Expressionism', 'Modern'];
